trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile.dockerfile'
        tags: |
          $(tag)
          
    - script: docker images
      displayName: List Docker Images
    - task: Docker@2
      displayName: Push an image
      inputs:
        containerRegistry: 'docker-registery'  # Make sure this is correctly named
        repository: 'amir3170/project'
        command: push
        tags: |
          $(tag)
