trigger:
  branches:
    include:
    - main  # Assuming you want to trigger the build on changes to the main branch
 
resources:
- repo: self
 
variables:
  tag: '$(Build.BuildId)'
  imageName: 'amir3170/project:$(tag)'
 
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and tag an image
      inputs:
        #containerRegistry: 'docker-registery'
        #repository: 'amir3170/project'
        command: build
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile.dockerfile'
        tags: |
          $(tag)
 
    - task: Docker@2
      displayName: Log in to Docker Hub
      inputs:
        command: login
        containerRegistry: 'docker-registery'
 
    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: 'docker-registery'
        repository: 'amir3170/project'
        command: push
        tags: |
          $(tag)